language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq default-jdk g++ make
  - echo -e "127.0.0.1 localhost\n127.0.0.1 travis001.onddo.com" | sudo tee -a /etc/hosts
  - sudo hostname 'travis001.onddo.com'
  - hostname | sudo tee /etc/hostname
  - npm install -g jshint || true
