language: node_js
node_js:
  - "0.10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq default-jdk g++ make
  - echo "127.0.0.1 $HOSTNAME" | sudo tee -a /etc/hosts
env:
  - JAVA_HOME="/usr/lib/jvm/default-java"
