language: node_js

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - default-jdk
    - g++
    - make

node_js:
- "0.10"
- "0.11"
- "0.12"
- "4.0"
- "4.1"

before_install:
- export CXX=g++
- npm install -g jshint || true
